Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/07f5b601ee
  logs: logs/Scannet++/07f5b601ee
  output: output/Scannet++/07f5b601ee
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[0.4068989763893689, 6.910014890597941], [-3.436454725572229, 2.210716788549467],
    [-5.757394675581352, 0.7430463885060132]]
  first_min_area: 2000
  marching_cubes_bound: [[0.4068989763893689, 6.910014890597941], [-3.436454725572229,
    2.210716788549467], [-5.757394675581352, 0.7430463885060132]]
output_dimension_semantic: 500
scale: 1
