Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/39f36da05b
  logs: logs/Scannet++/39f36da05b
  output: output/Scannet++/39f36da05b
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: '[[-5.489612207340957, 7.748007716378668], [-5.253829310610758, 3.0640555963124037],
    [-7.050291981424051, 5.156117108194174]]'
  first_min_area: 2000
  marching_cubes_bound: '[[-5.489612207340957, 7.748007716378668], [-5.253829310610758,
    3.0640555963124037], [-7.050291981424051, 5.156117108194174]]'
output_dimension_semantic: 500
scale: 1
