Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/41b00feddb
  logs: logs/Scannet++/41b00feddb
  output: output/Scannet++/41b00feddb
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-24.50748406649022, -4.887259792267404], [-7.114516468034494, 4.633584871572431],
    [-17.004191755732005, 2.398813279485873]] 
  first_min_area: 2000
  marching_cubes_bound:  [[-24.50748406649022, -4.887259792267404], [-7.114516468034494,
    4.633584871572431], [-17.004191755732005, 2.398813279485873]] 
output_dimension_semantic: 500
scale: 1
