inherit_from: configs/Scannet++/scannet.yaml
mapping:

  bound: [[-20.250008496138566, -11.907409896717752],[-4.112293300073711, 0.7526168358402805],[-8.185245753536197, -2.763493021909295]]
  #bound: [[-4,4],[-4,4],[-4,4]]
  marching_cubes_bound: [[-20.250008496138566, -11.907409896717752],[-4.112293300073711, 0.7526168358402805],[-8.185245753536197, -2.763493021909295]]
  first_min_area: 3000
data:
# TODO 
  input_folder: Dataset/41b00feddb
  output: output/Scannet++/41b00feddb
  logs: logs/Scannet++/41b00feddb
Segmenter:
  samplePixelFarther: 8
  normalizePointNumber: 5
  depthCondition: 0.1 #0.005 #0.0 # 0.3
  border: 30
  every_frame: 10
  smallestMaskSize: 3000 # 10000
output_dimension_semantic: 500
scale: 1
#yload_cpt: /home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00049.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01000.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00499.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01999.tar
#make images smaller 