Segmenter:
  border: 20
  depthCondition: 0.15
  every_frame: 5
  normalizePointNumber: 8
  samplePixelFarther: 8
  smallestMaskSize: 2000

tracking:
  gt_camera: True
data:
  #input_folder: Dataset/56a0ec536c
  #logs: logs/Scannet++/56a0ec536c
  #output: output/Scannet++/56a0ec536c

  input_folder: Dataset/56a0ec536c
  logs: logs/Scannet++/56a0ec536c
  output: output/Scannet++/56a0ec536c
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-4.070793785694184, 4.856251816133856], [-2.4926024940348896, 4.1097323130626515],
    [-5.196354947093756, 4.103471723382164]] 
  first_min_area: 3000
  marching_cubes_bound:  [[-4.070793785694184, 4.856251816133856], [-2.4926024940348896,
    4.1097323130626515], [-5.196354947093756, 4.103471723382164]] 

#load_cpt: 'output/Scannet++/56a0ec536c/ckpts/01999.tar'

output_dimension_semantic: 500
scale: 1
