Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 3000
data:
  input_folder: Dataset/56a0ec536c
  logs: logs/Scannet++/56a0ec536c
  output: output/Scannet++/56a0ec536c
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-4.070793785694184, 4.856251816133856], [-2.4926024940348896, 4.1097323130626515],
    [-5.196354947093756, 4.103471723382164]] 
  first_min_area: 3000
  marching_cubes_bound:  [[-4.070793785694184, 4.856251816133856], [-2.4926024940348896,
    4.1097323130626515], [-5.196354947093756, 4.103471723382164]] 
output_dimension_semantic: 500
scale: 1
