Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/56a0ec536c
  logs: logs/Scannet++/56a0ec536c_ef5
  output: output/Scannet++/56a0ec536c_ef5
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  every_frame: 5
  mesh_freq: 50
  bound: [[-1.5586548233135855, 7.762284228551966], [-2.3390342807180935, 6.098653785055868],
    [-0.2664747972243242, 5.056522917208074]]
  first_min_area: 2000
  marching_cubes_bound: [[-1.5586548233135855, 7.762284228551966], [-2.3390342807180935,
    6.098653785055868], [-0.2664747972243242, 5.056522917208074]]
output_dimension_semantic: 500
scale: 1
