inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-4.070793785694184, 4.856251816133856], [-2.4926024940348896, 4.1097323130626515], [-5.196354947093756, 4.103471723382164]]

  #bound: [[-4,4],[-4,4],[-4,4]]
  marching_cubes_bound: [[-4.070793785694184, 4.856251816133856], [-2.4926024940348896, 4.1097323130626515], [-5.196354947093756, 4.103471723382164]]

  first_min_area: 3000
data:
# TODO 
  input_folder: /home/rozenberszki/D_Project/wsnsl/Dataset/56a0ec536c
  output: output/Scannet++/56a0ec536c
  logs: logs/Scannet++/56a0ec536c
Segmenter:
  samplePixelFarther: 8
  normalizePointNumber: 5
  depthCondition: 0.1 #0.005 #0.0 # 0.3
  border: 30
  every_frame: 10
  smallestMaskSize: 3000 # 10000
output_dimension_semantic: 500
scale: 1
#yload_cpt: /home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00049.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01000.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00499.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01999.tar
#make images smaller 