Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/5fb5d2dbf2
  logs: logs/Scannet++/5fb5d2dbf2
  output: output/Scannet++/5fb5d2dbf2
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-3.022592696637439, 8.895336811511498], [-4.618500089949689, 6.148802828462057],
    [-7.540831599156962, 6.480087916397451]]
  first_min_area: 2000
  marching_cubes_bound: [[-3.022592696637439, 8.895336811511498], [-4.618500089949689,
    6.148802828462057], [-7.540831599156962, 6.480087916397451]]
output_dimension_semantic: 500
scale: 1
