Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/8b5caf3398
  logs: logs/Scannet++/8b5caf3398
  output: output/Scannet++/8b5caf3398
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-2.919554124365529, 5.977171390725077], [-2.7563677767638715, 3.9751238634494404],
    [-6.215323185517098, 2.968945879673896]] 
  first_min_area: 2000
  marching_cubes_bound:  [[-2.919554124365529, 5.977171390725077], [-2.7563677767638715,
    3.9751238634494404], [-6.215323185517098, 2.968945879673896]] 
output_dimension_semantic: 500
scale: 1
