Segmenter:
  border: 20
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/8b5caf3398
  logs: logs/Scannet++/8b5caf3398
  output: output/Scannet++/8b5caf3398
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-0.9286883331262248, 7.25511682959352], [-2.0847577252789176, 6.328670619979754],
    [-0.6221559592293291, 3.9850013105209037]]
  first_min_area: 2000
  marching_cubes_bound: [[-0.9286883331262248, 7.25511682959352], [-2.0847577252789176,
    6.328670619979754], [-0.6221559592293291, 3.9850013105209037]]
output_dimension_semantic: 500
scale: 1
