inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-5,5],[-5,5],[-5,5]]
  #bound: [[-4,4],[-4,4],[-4,4]]
  marching_cubes_bound: [[-5,5],[-5,5],[-5,5]]
  first_min_area: 3000
data:
# TODO 
  input_folder: Dataset/8b5caf3398
  output: output/Scannet++/8b5caf3398
  logs: logs/Scannet++/8b5caf3398
Segmenter:
  samplePixelFarther: 8
  normalizePointNumber: 5
  depthCondition: 0.1 #0.005 #0.0 # 0.3
  border: 30
  every_frame: 10
  smallestMaskSize: 3000 # 10000
output_dimension_semantic: 500
scale: 1
#yload_cpt: /home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00049.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01000.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00499.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01999.tar
#make images smaller 