Segmenter:
  border: 10
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 1000
data:
  input_folder: Dataset/8d563fc2cc
  logs: logs/Scannet++/8d563fc2cc
  output: output/Scannet++/8d563fc2cc
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-2.425218839466479, 8.658057988968745], [-2.1207123122673055, 7.089903578380182],
    [-2.4548530170351617, 4.635910851628596]]
  first_min_area: 2000
  marching_cubes_bound: [[-2.425218839466479, 8.658057988968745], [-2.1207123122673055,
    7.089903578380182], [-2.4548530170351617, 4.635910851628596]]
output_dimension_semantic: 500
scale: 1
