inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-9.582782840768061, 3.6002308698973726], [-4.9975736820317955, 5.152613078188253], [-13.65986657056969, -0.5395026014014412]]
  #bound: [[-4,4],[-4,4],[-4,4]]
  marching_cubes_bound: [[-9.582782840768061, 3.6002308698973726], [-4.9975736820317955, 5.152613078188253], [-13.65986657056969, -0.5395026014014412]]
  first_min_area: 3000
data:
# TODO 
  input_folder: Dataset/98b4ec142f
  output: output/Scannet++/98b4ec142f
  logs: logs/Scannet++/98b4ec142f
Segmenter:
  samplePixelFarther: 8
  normalizePointNumber: 5
  depthCondition: 0.1 #0.005 #0.0 # 0.3
  border: 30
  every_frame: 10
  smallestMaskSize: 3000 # 10000
output_dimension_semantic: 500
scale: 1
#yload_cpt: /home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00049.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01000.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00499.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01999.tar
#make images smaller 