Segmenter:
  border: 20
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 8
  samplePixelFarther: 8
  smallestMaskSize: 3000
data:
  input_folder: Dataset/98b4ec142f
  logs: logs/Scannet++/98b4ec142f
  output: output/Scannet++/98b4ec142f
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-9.582782840768061, 3.6002308698973726], [-4.9975736820317955, 5.152613078188253],
    [-13.65986657056969, -0.5395026014014412]] 
  first_min_area: 3000
  marching_cubes_bound:  [[-9.582782840768061, 3.6002308698973726], [-4.9975736820317955,
    5.152613078188253], [-13.65986657056969, -0.5395026014014412]] 
output_dimension_semantic: 500
scale: 1
