Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/b20a261fdf
  logs: logs/Scannet++/b20a261fdf
  output: output/Scannet++/b20a261fdf
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-2.721766720031403, 12.863155382095279], [-4.187328205529724, 6.7582327172962],
    [-9.663427104574534, 6.541482654411162]] 
  first_min_area: 2000
  marching_cubes_bound:  [[-2.721766720031403, 12.863155382095279], [-4.187328205529724,
    6.7582327172962], [-9.663427104574534, 6.541482654411162]] 
output_dimension_semantic: 500
scale: 1
