Segmenter:
  border: 10
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/b20a261fdf
  logs: logs/Scannet++/b20a261fdf
  output: output/Scannet++/b20a261fdf
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-1.7248667639229098, 8.383113244826705], [-3.1570403710739727, 6.723165048529641],
    [-2.7347176550338643, 4.415264583007938]]
  first_min_area: 2000
  marching_cubes_bound: [[-1.7248667639229098, 8.383113244826705], [-3.1570403710739727,
    6.723165048529641], [-2.7347176550338643, 4.415264583007938]]
output_dimension_semantic: 500
scale: 1
