inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound: [[-2.721766720031403, 12.863155382095279], [-4.187328205529724, 6.7582327172962], [-9.663427104574534, 6.541482654411162]]


  #bound: [[-4,4],[-4,4],[-4,4]]
  marching_cubes_bound: [[-2.721766720031403, 12.863155382095279], [-4.187328205529724, 6.7582327172962], [-9.663427104574534, 6.541482654411162]]


  first_min_area: 3000
data:
# TODO 
  input_folder: Dataset/b20a261fdf
  output: output/Scannet++/b20a261fdf
  logs: logs/Scannet++/b20a261fdf
Segmenter:
  samplePixelFarther: 8
  normalizePointNumber: 5
  depthCondition: 0.05 #0.005 #0.0 # 0.3
  border: 30
  every_frame: 10
  smallestMaskSize: 300 # 10000
output_dimension_semantic: 500
scale: 1
#yload_cpt: /home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00049.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01000.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/00499.tar #/home/rozenberszki/D_Project/wsnsl/output/Scannet++/56a0ec536c/ckpts/01999.tar
#make images smaller 