Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 5
  samplePixelFarther: 8
  smallestMaskSize: 3000
data:
  input_folder: Dataset/fe1733741f
  logs: logs/Scannet++/fe1733741f
  output: output/Scannet++/fe1733741f
inherit_from: configs/Scannet++/scannet.yaml
mapping:
  bound:  [[-11.870805646465676, -0.08686367641626536], [-5.2383272854987215, 5.323754296533068],
    [-2.8142115403743437, 9.441466688237004]] 
  first_min_area: 3000
  marching_cubes_bound:  [[-11.870805646465676, -0.08686367641626536], [-5.2383272854987215,
    5.323754296533068], [-2.8142115403743437, 9.441466688237004]] 
output_dimension_semantic: 500
scale: 1
