dataset: 'scannet_panoptic'
inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-4.59896427, 13.58024123],[-5.71416288,  7.88278209],[-1.8909007,   3.3331548 ]]
  marching_cubes_bound: [[-4.59896427, 13.58024123],[-5.71416288,  7.88278209],[-1.8909007,   3.3331548 ]]
  every_frame: 1
  keyframe_every: 6
  first_min_area: 2000
data:
  input_folder: Datasets/Scannet/scene0300_01
  output:  output/scannet/scene0300_01
  logs: logs/scannet/scene0300_01
output_dimension_semantic: 250
Segmenter:
  samplePixelFarther: 5
  normalizePointNumber: 7
  depthCondition: 0.05 #0.005 #0.0 
  border: 10
  every_frame: 2
  smallestMaskSize: 2000
 
cam:
  png_depth_scale: 1000
  H: 480
  W: 640
  fx: 577.870605
  fy: 577.870605
  cx: 319.5
  cy: 239.5
