dataset: 'scannet_panoptic'
inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-3.424508016677205, 5.791599599383032], [-0.6927954593774346, 5.143384973240208], [-0.4796076272868053, 1.7210238644389042]]
  marching_cubes_bound: [[-3.424508016677205, 5.791599599383032], [-0.6927954593774346, 5.143384973240208], [-0.4796076272868053, 1.7210238644389042]]
  first_min_area: 2000
  every_frame: 1
  keyframe_every: 6
data:
  input_folder: Datasets/Scannet/scene0693_00
  output:  output/scannet/scene0693_00
  logs: logs/scannet/scene0693_00
output_dimension_semantic: 200
Segmenter:
  samplePixelFarther: 5
  normalizePointNumber: 7
  depthCondition: 0.1 #0.005 #0.0 
  border: 10
  smallestMaskSize: 2000 # 10000
  every_frame: 2
