dataset: 'scannet_panoptic'
inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-3.424508016677205, 5.791599599383032], [-0.6927954593774346, 5.143384973240208], [-0.4796076272868053, 1.7210238644389042]]

  marching_cubes_bound: [[-3.424508016677205, 5.791599599383032], [-0.6927954593774346, 5.143384973240208], [-0.4796076272868053, 1.7210238644389042]]

data:
  input_folder: Datasets/Scannet/scene0693_00
  output:  output/scannet/scene0693_00
  logs: logs/scannet/scene0693_00
output_dimension_semantic: 400
Segmenter:
  samplePixelFarther: 4
  normalizePointNumber: 8
  depthCondition: 0.1 #0.005 #0.0 
  border: 20
  smallestMaskSize: 5000 # 10000
  every_frame: 10
cam:
  png_depth_scale: 1000
  H: 480
  W: 640
  fx: 577.870605
  fy: 577.870605
  cx: 319.5
  cy: 239.5
full_slam: True