dataset: 'scannet_panoptic'
inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.5214331239823449, 4.527215864201953], [-0.5760537104577677, 4.405228336532577], [0.20521706203409074, 1.3631349670874848]]

  marching_cubes_bound: [[-0.5214331239823449, 4.527215864201953], [-0.5760537104577677, 4.405228336532577], [0.20521706203409074, 1.3631349670874848]]
  every_frames: 2
  keyframe_every: 12
data:
  input_folder: Datasets/Scannet/scene0427_00
  output:  output/scannet/scene0427_00
  logs: logs/scannet/scene0427_00
output_dimension_semantic: 400
Segmenter:
  samplePixelFarther: 4
  normalizePointNumber: 10
  depthCondition: 0.05 #0.005 #0.0 
  border: 20
  smallestMaskSize: 5000 # 10000
  every_frame: 4
cam:
  png_depth_scale: 1000
  H: 480
  W: 640
  fx: 577.870605
  fy: 577.870605
  cx: 319.5
  cy: 239.5
full_slam: True