dataset: 'scannet_panoptic'
inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.7676750599960958, 6.624886698974093], [-3.1017380409592854, 12.215550387109344], [-6.376166552614103, 2.225511913242739]]

  marching_cubes_bound: [[-0.7676750599960958, 6.624886698974093], [-3.1017380409592854, 12.215550387109344], [-6.376166552614103, 2.225511913242739]]
data:
  input_folder: Datasets/Scannet/scene0354_00
  output: output_imap/scannet/scene0354_00
  logs: logs/scannet/scene0354_00
output_dimension_semantic: 400
Segmenter:
  samplePixelFarther: 4
  normalizePointNumber: 5
  depthCondition: 0.1 #0.005 #0.0 
  border: 30
  smallestMaskSize: 5000 # 10000
  every_frame: 10
tracking:
  gt_camera: False
cam:
  png_depth_scale: 1000
  H: 480
  W: 640
  fx: 577.870605
  fy: 577.870605
  cx: 319.5
  cy: 239.5
full_slam: True