dataset: 'scannet_panoptic'
inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-5, 12],[-5.2, 12.7],[-0.3, 1.4]]
  marching_cubes_bound: [[-5, 12],[-5.2, 12.7],[-0.3, 1.4]]
data:
  input_folder: Datasets/Scannet/scene0423_02_panoptic
  output: output/scannet/scans/scene0423_02_panoptic
  logs: logs/scannet/scans/scene0423_02_panoptic
output_dimension_semantic: 400
Segmenter:
  samplePixelFarther: 4
  normalizePointNumber: 10
  depthCondition: 0.05 #0.005 #0.0
  border: 30
  smallestMaskSize: 3000 # 10000
tracking:
  gt_camera: True
cam:
  png_depth_scale: 1000
  H: 480
  W: 640
  fx: 577.870605
  fy: 577.870605
  cx: 319.5
  cy: 239.5
full_slam: True
