inherit_from: configs/Own/own.yaml
mapping:
  bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
  marching_cubes_bound: [[-5.5,5.9],[-6.7,5.4],[-4.7,5.3]]
data:
  input_folder: Datasets/Replica/office0
  output: output/Own/office0
  logs: logs/office0