inherit_from: configs/Own/own.yaml
mapping:
  first_min_area: 0
  max_frames: 200
  bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
  marching_cubes_bound: [[-6.7,5.1],[-7.5,4.9],[-2.8,3.5]]
data:
  input_folder: /home/rozenberszki/project/wsnsl/Datasets/Replica/office3
  output: output/Own/office3_Sm
  logs: logs/office3_Sm
output_dimension_semantic: 400
Segmenter:
  smallestMaskSize: 0 # 10000s
