dataset: 'replica'
coarse: True
meshing:
  eval_rec: True
  resolution: 256 # change to 512 for higher resolution geometry
tracking:
  vis_freq: 10
  vis_inside_freq: 25
  ignore_edge_W: 50 #100
  ignore_edge_H: 50 #100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 200
  iters: 10
  gt_camera: False
Segmenter:
  samplePixelFarther: 2
  normalizePointNumber: 7
  depthCondition: 0.05 #0.005 #0.0
  border: 10
  smallestMaskSize: 600 # 10000
  full_slam: True
  mask_generator: False # always False -> delete later
  #store: False    #if use_store True then store and store_vis have no effect
  use_stored: False
  store_vis: True
  store_vis_freq: 100 # not implemented yet
  num_clusters: 5
  border: 10
  overlap: 0.4 # makes more stable
  relevant: 0.3
  merging_parameter: 7 # if it really is the same object, then it should not have any problems eating the other mask even if for 10 frames
  every_frame: 10
  verbose: True
  hit_percent: 0.4

rendering:
  semantic_occupancy_multiplier: 10
mapping:
  first_min_area: 600
  use_vis: True
  no_vis_on_first_frame: True
  every_frame: 5
  points_per_instance: 4
  vis_freq: 200
  vis_inside_freq: 71
  vis_offset: 0 #we take the current frame - vis_offset for visualization #should not work at the moment
  use_mesh: True #whether to generate mesh during training, the creation of thefinal mesh only depends ecal_rec
  no_mesh_on_first_frame: True
  mesh_freq: 200
  ckpt_freq: 200
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 1000
  iters_first: 1000 #finetune
  iters: 70 #finetune
  w_color_loss: 0.2 #maybe finetune
  w_semantic_loss: 10 #finetuneS
  middle_iter_ratio: 0.4 #0.4 #finetune
  fine_iter_ratio: 0.6 #0.6 #finetune
  semantic_iter_ratio: 0.4 #0.4 #finetune
  stage:
    color: #maybe finetune, because our color results are not as good as in the original paper
      decoders_lr: 0.005
      coarse_lr: 0.0
      middle_lr: 0.005
      fine_lr: 0.005
      color_lr: 0.005
      semantic_lr: 0.0
    semantic: #finetune
      decoders_lr: 0.005
      coarse_lr: 0.0
      middle_lr: 0.0
      fine_lr: 0.0
      color_lr: 0.0
      semantic_lr: 0.4 #original: 0.005

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  crop_size: [340, 600]
  png_depth_scale: 6553.5 #for depth image in png format
  #crop_edge: 8
#parames2finetune: ['mapping', ]