dataset: 'replica'
meshing:
  eval_rec: True
  resolution: 512 # change to 512 for higher resolution geometry
tracking:
  path: '/home/koerner/Project/nice-slam/Datasets/Replica/room0/traj.txt'
  vis_freq: 10
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 200
  iters: 10
rendering:
  semantic_occupancy_multiplier: 10
mapping:
  min_area: 0
  use_vis: True
  no_vis_on_first_frame: False
  every_frame: 5
  points_per_instance: 5
  vis_freq: 5
  vis_inside_freq: 1599
  vis_offset: 0 #we take the current frame - vis_offset for visualization #should not work at the moment
  use_mesh: True #whether to generate mesh during training, the creation of thefinal mesh only depends ecal_rec
  no_mesh_on_first_frame: True
  mesh_freq: 10
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 10
  iters_first: 1600 #finetune
  iters: 200 #finetune
  w_color_loss: 0.2 #maybe finetune
  w_semantic_loss: 10 #finetune
  middle_iter_ratio: 0.4 #0.4 #finetune
  fine_iter_ratio: 0.6 #0.6 #finetune
  semantic_iter_ratio: 0.4 #0.4 #finetune
  stage:
    color: #maybe finetune, because our color results are not as good as in the original paper
      decoders_lr: 0.005
      coarse_lr: 0.0
      middle_lr: 0.005
      fine_lr: 0.005
      color_lr: 0.005
      semantic_lr: 0.0
    semantic: #finetune
      decoders_lr: 0.0
      coarse_lr: 0.0
      middle_lr: 0.0
      fine_lr: 0.0
      color_lr: 0.0
      semantic_lr: 0.4 #original: 0.005

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0

#parames2finetune: ['mapping', ]