dataset: 'replica'
meshing:
  eval_rec: True
tracking:
  vis_freq: 50
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 200
  iters: 10
mapping:
  use_vis: True
  no_vis_on_first_frame: True
  every_frame: 5
  vis_freq: 20
  vis_inside_freq: 99
  vis_offset: 2 #we take the current frame - vis_offset for visualization
  mesh_freq: 50
  ckpt_freq: 500
  keyframe_every: 50
  mapping_window_size: 5
  pixels: 1000
  iters_first: 3000 #finetune
  iters: 100 #finetune
  w_color_loss: 0.2 #maybe finetune
  w_semantic_loss: 10 #finetune
  middle_iter_ratio: 0.4 #0.4 #finetune
  fine_iter_ratio: 0.6 #0.6 #finetune
  semantic_iter_ratio: 0.4 #0.4 #finetune
  stage:
    color: #maybe finetune, because our color results are not as good as in the original paper
      decoders_lr: 0.005
      coarse_lr: 0.0
      middle_lr: 0.005
      fine_lr: 0.005
      color_lr: 0.005
      semantic_lr: 0.0
    semantic: #finetune
      decoders_lr: 0.00
      coarse_lr: 0.0
      middle_lr: 0.00
      fine_lr: 0.00
      color_lr: 0.0
      semantic_lr: 0.2 #original: 0.005

cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0

parames2finetune: ['mapping', ]