inherit_from: 'configs/Own/own.yaml'
#dataset: 'panoptic'
#tracking:
#  path: '/home/koerner/Project/nice-slam/Datasets/Replica/room0/traj.txt'
mapping:
  first_min_area: 0
  bound: [[-0.8793944, 6.8852057], [-1.1859794, 3.5122514], [-1.5273631, 1.2804066]] # [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-1, 7], [-1.2, 3.6], [-1.6, 1.3]]
  semantic_iter_ratio: 0.2 #0.4 #finetune
data:
  input_folder: 'Datasets/Replica/room0_panoptic'
  logs: 'logs/room0_panoptic_sms0'
  output: 'output/Own/room0_panoptic_sms0'
output_dimension_semantic: 700
tracking:
  lr: 0.0005      
  pixels: 1000
  iters: 200
  gt_camera: True
cam:
  png_depth_scale: 1000
  H: 480
  W: 640
  fx: 320.0
  fy: 320.0
  cx: 319.5
  cy: 239.5
  crop_size: [480, 640]
Segmenter:
  smallestMaskSize: 0 # 10000

