inherit_from: 'configs/Own/own.yaml'
mapping:
  bound: [[-7.0,2.8],[-4.6,4.3],[-3.0,2.9]]
  marching_cubes_bound: [[-7.0,2.8],[-4.6,4.3],[-3.0,2.9]]
data:
  input_folder: 'Demo_Data/room1_small'
  logs: 'logs/room1_small'
  output: 'output/Own/room1_small'
output_dimension_semantic: 50
load_cpt: /home/koerner/Project/wsnsl/output/Own/room1_small/ckpts/00059.tar