inherit_from: 'configs/Own/own.yaml'
#dataset: 'panoptic'
#tracking:
#  path: '/home/koerner/Project/nice-slam/Datasets/Replica/room0/traj.txt'
mapping:
  bound: [[-0.8793944, 6.8852057], [-1.1859794, 3.5122514], [-1.5273631, 1.2804066]] # [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-1, 7], [-1.2, 3.6], [-1.6, 1.3]]
data:
  input_folder: 'Datasets/Replica/room0_panoptic'
  logs: 'logs/room0_panoptic'
  output: 'output/Own/room0_panoptic'
output_dimension_semantic: 400
Segmenter:
  samplePixelFarther: 4
  normalizePointNumber: 10
  depthCondition: 0.05 #0.005 #0.0
  border: 30
  smallestMaskSize: 3000 # 10000
tracking:
  gt_camera: False
cam:
  png_depth_scale: 1000
  crop_size:
  H: 480
  W: 640
  fx: 320.0
  fy: 320.0
  cx: 319.5
  cy: 239.5
#load_cpt: '/home/rozenberszki/project/wsnsl/output/Own/room0_panoptic/ckpts/ef2_no_segmenter.tar'
full_slam: True


