inherit_from: 'configs/Own/own.yaml'
store: True
store_path: 'model/room0'
#tracking:
#  path: '/home/koerner/Project/nice-slam/Datasets/Replica/room0/traj.txt'
#/home/koerner/Project/nice-slam/Datasets/Replica/room0_small
mapping:
  bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
data:
  input_folder: '/home/koerner/Project/nice-slam/Datasets/Replica/room0_small'
  logs: 'logs/room0_small'
  output: 'output/Own/room0_small'
output_dimension_semantic: 200