inherit_from: 'configs/Own/own.yaml'
#tracking:
#  path: '/home/koerner/Project/nice-slam/Datasets/Replica/room0/traj.txt'
mapping:
  first_min_area: 2000
  bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
data:
  input_folder: '/home/rozenberszki/project/wsnsl/Datasets/Replica/room0'
  logs: 'logs/room0'
  output: 'output/Own/room0_Bm'
output_dimension_semantic: 500
Segmenter:
  every_frame: 40
  smallestMaskSize: 2000 # 10000s
tracking:
  gt_camera: True
meshing:
  confidence_threshold: 0.2
