inherit_from: 'configs/Own/own.yaml'
#tracking:
#  path: '/home/koerner/Project/nice-slam/Datasets/Replica/room0/traj.txt
mapping:
  bound: [[-7.0,2.8],[-4.6,4.3],[-3.0,2.9]]
  marching_cubes_bound: [[-7.0,2.8],[-4.6,4.3],[-3.0,2.9]]
data:
  input_folder: 'Datasets/Replica/room1_small'
  logs: 'logs/room1_small'
  output: 'output/Own/room1_small'
output_dimension_semantic: 300