inherit_from: configs/Own/own.yaml
mapping:
  bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
  marching_cubes_bound: [[-2.9,8.9],[-3.2,5.5],[-3.5,3.3]]
data:
  input_folder: Datasets/Own/room0
  output: output/Own/room0
output_dimension_semantic: 101
