inherit_from: configs/Own/own.yaml
mapping:
  bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
  marching_cubes_bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
data:
  input_folder: /home/rozenberszki/project/wsnsl/Datasets/office1
  output: output/Own/office1_post
  logs: logs/office1_post
output_dimension_semantic: 250
Segmenter:
  full_slam: False