inherit_from: configs/Own/own.yaml
mapping:
  bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
  marching_cubes_bound: [[-5.0,4.6],[-4.4,6.9],[-2.8,3.1]]
data:
  input_folder: /home/rozenberszki/project/wsnsl/Datasets/office2
  output: output/Own/office2_post
  logs: logs/office2_post
output_dimension_semantic: 400
Segmenter:
  full_slam: False