Segmenter:
  border: 20
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 2000
data:
  input_folder: Dataset/07f5b601ee
  logs: logs/Scannet++NoTruth/07f5b601ee
  output: output/Scannet++NoTruth/07f5b601ee
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  iters_first: 2000 #finetune
  iters: 80 #finetune
  max_frames: 4000
  keyframe_every: 10
  bound: [[1.4986106761319469, 5.8388683617158526], [-2.373721660606694, 1.0810422625671243],
    [-4.701736504782533, -1.0469358333820535]]
  first_min_area: 2000
  every_frame: 2
  marching_cubes_bound: [[1.4986106761319469, 5.8388683617158526], [-2.373721660606694,
    1.0810422625671243], [-4.701736504782533, -1.0469358333820535]]
output_dimension_semantic: 500
scale: 1
