Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/1841a0b525
  logs: logs/Scannet++NoTruth/1841a0b525
  output: output/Scannet++NoTruth/1841a0b525
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-1.2078443005300885, 5.246005583395376], [-4.602589664840288, 1.366622586072622],
    [2.8909504924369367, 10.0863001186869]]
  first_min_area: 2000
  marching_cubes_bound: [[-1.2078443005300885, 5.246005583395376], [-4.602589664840288,
    1.366622586072622], [2.8909504924369367, 10.0863001186869]]
output_dimension_semantic: 500
scale: 1
