Segmenter:
  border: 10
  depthCondition: 0.05
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 2
  smallestMaskSize: 1000
data:
  input_folder: Dataset/39f36da05b
  logs: logs/Scannet++NoTruth/39f36da05b
  output: output/Scannet++NoTruth/39f36da05b
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-2.413767676134533, 5.438840218870353], [-4.355611194078378, 0.03493988255763114],
    [-4.651168166905448, 3.7007712469428697]]
  first_min_area: 2000
  marching_cubes_bound: [[-2.413767676134533, 5.438840218870353], [-4.355611194078378,
    0.03493988255763114], [-4.651168166905448, 3.7007712469428697]]
output_dimension_semantic: 500
scale: 1
