Segmenter:
  border: 20
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 2000
data:
  input_folder: Dataset/7cd2ac43b4
  logs: logs/Scannet++NoTruth/7cd2ac43b4
  output: output/Scannet++NoTruth/7cd2ac43b4
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[3.049461380983199, 11.049959113518218], [-2.5945950312402446, 3.797058918759644],
    [14.062973742734567, 20.414138248809163]]
  first_min_area: 2000
  marching_cubes_bound: [[3.049461380983199, 11.049959113518218], [-2.5945950312402446,
    3.797058918759644], [14.062973742734567, 20.414138248809163]]
output_dimension_semantic: 500
scale: 1
