Segmenter:
  border: 20
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 2000
data:
  input_folder: Dataset/8b5caf3398
  logs: logs/Scannet++NoTruth/8b5caf3398
  output: output/Scannet++NoTruth/8b5caf3398
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-0.18959761995833913, 4.784583802899594], [-1.3260768466615793, 2.3690948853115974],
    [-4.713016384827225, 1.3356648639675324]]
  first_min_area: 2000
  marching_cubes_bound: [[-0.18959761995833913, 4.784583802899594], [-1.3260768466615793,
    2.3690948853115974], [-4.713016384827225, 1.3356648639675324]]
output_dimension_semantic: 500
scale: 1
