Segmenter:
  border: 10
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 1000
data:
  input_folder: Dataset/8d563fc2cc
  logs: logs/Scannet++NoTruth/8d563fc2cc
  output: output/Scannet++NoTruth/8d563fc2cc
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-9.040775117270343, -0.38574336771289364], [-3.618663379795652, 2.343566030488349],
    [-3.4300371565824737, 4.166273754028186]]
  first_min_area: 2000
  marching_cubes_bound: [[-9.040775117270343, -0.38574336771289364], [-3.618663379795652,
    2.343566030488349], [-3.4300371565824737, 4.166273754028186]]
output_dimension_semantic: 500
scale: 1
