Segmenter:
  border: 10
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/b20a261fdf
  logs: logs/Scannet++NoTruth/b20a261fdf
  output: output/Scannet++NoTruth/b20a261fdf
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[0.951785098396134, 7.638032171011571], [-2.867397653608488, 2.4266228419539155],
    [-5.717170856407959, 5.180330394333307]]
  first_min_area: 2000
  marching_cubes_bound: [[0.951785098396134, 7.638032171011571], [-2.867397653608488,
    2.4266228419539155], [-5.717170856407959, 5.180330394333307]]
output_dimension_semantic: 500
scale: 1
