Segmenter:
  border: 30
  depthCondition: 0.1
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/c413b34238
  logs: logs/Scannet++NoTruth/c413b34238
  output: output/Scannet++NoTruth/c413b34238
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-2.8556170376537673, 7.431240555900711], [-3.522249168074148, 6.475279476186233],
    [-1.3604121703689813, 3.6791111454687764]]
  first_min_area: 2000
  marching_cubes_bound: [[-2.8556170376537673, 7.431240555900711], [-3.522249168074148,
    6.475279476186233], [-1.3604121703689813, 3.6791111454687764]]
output_dimension_semantic: 500
scale: 1
