Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 10
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/c413b34238
  logs: logs/Scannet++NoTruth/c413b34238
  output: output/Scannet++NoTruth/c413b34238
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-2.021292355001093, 3.8420977180188784], [-2.02263064144854, 2.945654116488232],
    [-3.806884196096883, 0.19260914249389166]]
  first_min_area: 2000
  marching_cubes_bound: [[-2.021292355001093, 3.8420977180188784], [-2.02263064144854,
    2.945654116488232], [-3.806884196096883, 0.19260914249389166]]
output_dimension_semantic: 500
scale: 1
