Segmenter:
  border: 30
  depthCondition: 0.1
  every_frame: 1
  normalizePointNumber: 7
  samplePixelFarther: 8
  smallestMaskSize: 2000
data:
  input_folder: Dataset/fe1733741f
  logs: logs/Scannet++NoTruth/fe1733741f
  output: output/Scannet++NoTruth/fe1733741f
inherit_from: configs/Scannet++NoTruth/scannet.yaml
mapping:
  bound: [[-8.628450408337343, -1.503454298852032], [-4.203381789784687, 2.595115601875445],
    [-1.6950727021373329, 6.987077698608234]]
  first_min_area: 2000
  marching_cubes_bound: [[-8.628450408337343, -1.503454298852032], [-4.203381789784687,
    2.595115601875445], [-1.6950727021373329, 6.987077698608234]]
output_dimension_semantic: 500
scale: 1
