Segmenter:
  border: 10
  depthCondition: 0.1
  every_frame: 2
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 2000
data:
  input_folder: Datasets/ScanNet_orig/scene0011_00
  logs: logs/ScanNet_orig/scene0011_00_every
  output: output/ScanNet_orig/scene0011_00_every
inherit_from: configs/ScanNet_orig_every/scannet_orig.yaml
mapping:
  bound: [[-0.058492072892132985, 7.571544732080833], [-0.9260770880714251, 8.883156326845633],[-0.2775422830796035, 2.8201318347531097]]
  first_min_area: 2000
  marching_cubes_bound: [[-0.058492072892132985, 7.571544732080833], [-0.9260770880714251,8.883156326845633], [-0.2775422830796035, 2.8201318347531097]]
output_dimension_semantic: 400
