Segmenter:
  border: 10
  depthCondition: 0.1
  every_frame: 2
  normalizePointNumber: 7
  samplePixelFarther: 5
  smallestMaskSize: 2000
data:
  input_folder: Datasets/ScanNet_orig/scene0671_00
  logs: logs/ScanNet_orig/scene0671_00_every
  output: output/ScanNet_orig/scene0671_00_every
inherit_from: configs/ScanNet_orig_every/scannet_orig.yaml
mapping:
  bound: [[-0.8385696101662168, 7.124459527425144], [0.5655418787579665, 6.838000904571226], [-0.601798005038068, 1.328600586504111]]
  first_min_area: 2000
  marching_cubes_bound: [[-0.8385696101662168, 7.124459527425144], [0.5655418787579665, 6.838000904571226], [-0.601798005038068, 1.328600586504111]]
output_dimension_semantic: 400
